name: 'deploy-infrastructure'
on: workflow_dispatch
jobs:
  dev: # job
    name: 'dev' # name for job
    runs-on: ubuntu-latest
    environment:  'dev'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7 # ch
    - name: Terraform Init
      id: init 
      run: terraform init 
    # terraform validate
    - name: Terraform Validate
      id: validate
      run: terraform validate
    # terraform plan
    - name: Terraform Plan
      id: plan
      run: terraform plan 
